source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'nifty-generators', '0.4.2'
gem 'mongo', '1.1.5'
gem 'bson', '1.1.5'
gem 'bson_ext', '1.1.5', :require => false
gem 'mongoid', '2.0.0.beta.20'
gem 'cancan', '1.4.1'
gem 'activerecord'
gem 'gibbon'
gem 'geocoder'
gem 'devise', '1.2.rc'
gem 'omniauth', '0.2.0.beta5'
gem 'mongo_mapper'
